name: ardu
channels:
  - defaults
  - bioconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.4=h5505292_0
  - ca-certificates=2025.1.31=hf0a4a13_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py312hb23fbb9_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.55.8=py312h998013c_0
  - freetype=2.12.1=hadb7bae_2
  - kiwisolver=1.4.8=py312h2c4a281_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=28_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=28_hb3479ef_openblas
  - libcurl=8.11.1=h73640d1_0
  - libcxx=19.1.7=ha82da77_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.6.4=h286801f_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=28_hc9a63f6_openblas
  - liblzma=5.6.4=h39f12f2_0
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.28=openmp_hf332438_1
  - libpng=1.6.46=h3783ad8_0
  - libsqlite=3.48.0=h3f77e49_1
  - libssh2=1.11.1=h9cc3647_0
  - libtiff=4.7.0=ha962b0a_2
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=19.1.7=hdb05f8b_0
  - matplotlib=3.10.0=py312h1f38498_0
  - matplotlib-base=3.10.0=py312hdbc7e53_0
  - munkres=1.0.7=py_1
  - ncurses=6.5=h5e97a16_3
  - numpy=2.2.3=py312h7c1f314_0
  - openjdk=11.0.13=h98b2900_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.4.1=h81ee809_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hcd31e36_1
  - pillow=11.1.0=py312h50aef2c_0
  - pip=25.0=pyh8b19718_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysam=0.23.0=py312h97124e9_0
  - python=3.12.8=hc22306f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h92ec313_1
  - ruptures=1.1.9=py312hbebd99a_2
  - scipy=1.15.1=py312hb7ffdcd_0
  - seaborn=0.13.2=py312hca03da5_1
  - setuptools=75.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snpeff=5.2=hdfd78af_1
  - tk=8.6.13=h5083fa2_1
  - tornado=6.4.2=py312hea69d52_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - unicodedata2=16.0.0=py312hea69d52_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.6=hb46c0d2_0
prefix: /Users/jeacl133/miniconda3/envs/ardu
